# Generated by Django 3.2.6 on 2021-08-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.review'),
        ),
    ]
