# Generated by Django 3.2.6 on 2021-08-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
